### ISSUE TITLE
Zoom in / Zoom out method scale amounts

### ISSUE THREAD

**Issue by emilyzhong** [mnogueron/react-easy-panzoom#12]
Hello! Is it possible to have a parameter to the `zoomIn` and `zoomOut` methods so they can scale a certain amount? I dug through the code a little and currently it scales by `this.props.zoomSpeed` * some multiplier, but it would be great to be able to determine a zoom speed separately for these methods :)

**Comment by mnogueron** [comment]
@emilyzhong Thank you for opening this issue!
It is a good improvement, I'll try to get it as soon as possible 😃

**Comment by mnogueron** [comment]
@emilyzhong `0.4.0` has just been released, including a new `zoomSpeed` parameter for `zoomIn` and `zoomOut` :)

**Comment by emilyzhong** [comment]
Thank you for such a speedy update ! 🎉
