### ISSUE TITLE
Transform matrix endpoint

### ISSUE THREAD

**Issue by emilyzhong** [mnogueron/react-easy-panzoom#14]
Hi! Would it be possible to have a method to get the current transform matrix? (Something like `getMatrixTransformString`, except instead of taking in arguments and formatting it into a string returning the css `transform` value?

Thanks in advance :)

**Comment by mnogueron** [comment]
Hi @emilyzhong, thank you for the issue.

You can easily access the `transform` value by using:
```js
panZoomRef.current.dragContainer.current.style.transform

...

<PanZoom ref={panZoomRef} ... />
```
as a quick fix.

Using the transform value relies on the internal implementation and can be dangerous to use. User should not expect this value to keep the same format. I'm a bit reluctent to make it open as it will force the library to keep the same implementation, but I will try to find a solution to that issue as you are not the first one asking 😃

**Comment by emilyzhong** [comment]
Thank you! Works like a charm 😄 Would love an update if some other solution is found in the future though!

**Comment by mnogueron** [comment]
@emilyzhong I am closing this issue as this has been solved. But feel free to reopen it, or open a PR if you find a good approach to that issue.
