### ISSUE TITLE
movement via arrow keys is not persisted in state

### ISSUE THREAD

**Issue by n1ru4l** [mnogueron/react-easy-panzoom#22]
**Reproduction:**

1. Use arrow keys for moving the content
2. Drag content and move it slightly (without releasing)
3. The content jumps back to the initial position (before the arrow key shiftings were applied)

**Possible Solution**:

It seems like there must be a `setState` call upon releasing the arrow keys (`onKeyUp`).

**Comment by mnogueron** [comment]
@n1ru4l Thank you for the issue! I will review your PR and get it released as soon as possible.
